using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PayrollSoft.Models
{
    public class MasterCodes
    {
        public string Code { get; set; }
        public DateTime DateAutogenerated { get; set; }
        public string Status { get; set; }
    }
}